name: git actions demo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "welcome to github actions"
          echo "welcome second line"
  test:
    runs-on: ubuntu-latest
    steps:
      name: Test
      run: echo "Test stage"

  deploy:
    runs-on: ubuntu-latest
    steps:
      name: Deploy
      run: echo "Deploy stage"
